# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['unified_game_automation/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('unified_game_automation/Tesseract', 'Tesseract'),
        ('app_icon.png', '.'),
    ],
    hiddenimports=[
        'PIL',
        'pywinauto',
        'keyboard',
        'mouse',
        'mss',
        'win32gui',
        'win32con',
        'win32ui',
        'win32api',
        'threading',
        'tkinter.ttk',
        'pytesseract',
        'cv2',
        'numpy',
        'pyautogui',
        'pydirectinput',
        'json',
        're',
        'os',
        'sys',
        'ctypes',
        'datetime',
        'tkinter.simpledialog',
        'PIL.Image'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Stellar_Automation',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=False,
    icon='app_icon.ico',
)
